// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from "../context/authcontext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//        <AuthProvider> 
//         {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "../context/authcontext";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata:Metadata = {
  title: "Doctors Appointment App",
  description: "Connect with doctors anytime, anywhere",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en" suppressHydrationWarning>
        {/* <head>
          <link rel="icon" href="/logo.png" sizes="any" />
        </head> */}
        <body className={`${inter.className}`}>

            <Header />
            <main className="min-h-screen">
              <AuthProvider> 
                {children}
              </AuthProvider>
            </main>
             
            <Toaster richColors />

            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-600">
                <p>ALL RIGHTS RESERVED BY MEDICARE</p>
              </div>
            </footer>
        </body>
      </html>
  );
}

